Repository wecode-bootcamp-korea/fullstack2-2nd-ourcodetrip-frontend, pull requests merged in 2021-11, with the labels that each got.

#29 [이원국] [공용] 모달, 팝업 관리를 위한 react-cookie 패키지 설치
  package-lock.json
  package.json
Labels: Status: 리뷰 요청

#25 [이욱창] footer 레이아웃 구현
  src/components/Footer/Footer.js
Labels: Status: 리뷰 요청

#26 [이욱창] navbar : 특정 경로가 아닐시 폰트색이 #fff가 되는 문제 해결
  src/components/TopNav/components/LowerNav.js
  src/components/TopNav/components/UpperNav.js
  src/components/TopNav/navListData.json
Labels: Status: 리뷰 요청

#38 [이욱창] 네비바 width고정, cities페이지 폰트색 수정
  src/components/TopNav/components/LowerNav.js
  src/components/TopNav/components/UpperNav.js
  src/components/TopNav/components/UserDropdown.js
  src/components/TopNav/navListData.json
Labels: Status: 리뷰 요청

#33 [이욱창] 리스트페이지 카테고리 아코디언 구현
  public/data/tourTicketCategories.json
  public/images/mainCategory/0.png
  public/images/mainCategory/1.png
  public/images/mainCategory/2.png
  public/images/mainCategory/3.png
  public/images/mainCategory/4.png
  public/images/mainCategory/5.png
  public/images/mainCategory/6.png
  public/images/mainCategory/7.png
  public/images/mainCategory/8.png
  public/images/mainCategory/9.png
  src/Routes.js
  src/components/List/Collapse.js
  src/hooks/tourTicketHook.js
  src/pages/TourTicket/List.js
  src/pages/TourTicket/components/TourTicketCategory.js
  src/store/index.js
  src/store/tourTicketSlice.js
  src/utils/categoryLinks.js
Labels: Status: 리뷰 요청

#36 [이원국] 투어티켓 리스트 페이지 필터, 솔팅, 페이지네이션 레이아웃 및 컴포넌트 구현 완료
  public/data/pagenation.json
  src/Routes.js
  src/components/Carousel/Cards.js
  src/components/Carousel/defaultOptions.js
  src/components/Footer/Footer.js
  src/components/List/List.js
  src/components/List/ListFilter.js
  src/components/List/components/ConfirmTypeFilter.js
  src/components/List/components/DateFilters.js
  src/components/List/components/PriceFilter.js
  src/components/List/components/RatingFilter.js
  src/hooks/filteringHook.js
  src/hooks/tourTicketHook.js
  src/pages/TourTicket/List.js
  src/pages/TourTicket/TourTicketList.js
  src/pages/TourTicket/components/TourTicketCategory.js
  src/store/filteringSlice.js
  src/store/index.js
  src/store/tourTicketSlice.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#35 [이욱창] 푸터 하단 링크태그 오류 해결 및 css네스팅 제거
  src/components/Footer/Footer.js
Labels: Status: 리뷰 요청

#41 [이원국] [위시리스트] 레이아웃 및 기능 구현
  public/data/cities.json
  public/data/suggestion1.json
  public/data/suggestion2.json
  public/data/suggestion3.json
  public/data/suggestion4.json
  public/data/suggestion5.json
  public/data/wishlist.json
  public/images/favicon.ico
  public/index.html
  src/Routes.js
  src/components/Carousel/Carousel.js
  src/pages/WishList/WishList.js
  src/pages/WishList/components/EmptyList.js
Labels: Status: 리뷰 요청

#40 [이원국] [hotfix] 쿼리 솔팅값 초기화시 변조되는 문제 해결
  src/store/tourTicketSlice.js
Labels: Status: 수정 요청

#43 [이원국] [공용] 404 Not Found 페이지 구현
  src/Routes.js
  src/components/NotFound/NotFound.js
Labels: Status: 리뷰 요청

#44 [이욱창] 유저 리듀서에 수정기능추가, 테스트 추가, 로컬스토리지 저장 기능 추가
  package-lock.json
  package.json
  public/images/defaultUserIcon.png
  src/components/TopNav/components/UpperNav.js
  src/components/TopNav/components/UserDropdown.js
  src/hooks/userHook.js
  src/index.js
  src/store/index.js
  src/store/userSlice.js
  src/store/userSlice.spec.js
Labels: Status: 리뷰 요청

#28 [이민재] 프로필 관리 및 편집 기능/레이아웃 구현
  .gitignore
  package-lock.json
  package.json
  public/data/profileData.json
  public/index.html
  src/Routes.js
  src/pages/User/Profile/AuthenticationPage/AuthenticationPage.js
  src/pages/User/Profile/EditingProfile.js
  src/pages/User/Profile/ManagingProfile.js
  src/pages/User/Profile/ProfileSection/EditingProfileMainSection.js
  src/pages/User/Profile/ProfileSection/ManagingProfileMainSection.js
  src/pages/User/Profile/ProfileSection/SideProfileSection.js
  src/pages/User/SignIn.js
  src/pages/User/SignUp.js
  src/store/userSlice.js
  src/utils/Kakao.js
Labels: Status: 기능 구현중

#8 [이은정] detail 기능 구현 중
  public/data/optionMock.json
  public/data/ticket.json
  public/data/ticketMock.json
  public/data/tour.json
  src/Routes.js
  src/pages/TourTicket/TourTicketDetail/TourTicketDetail.js
  src/pages/TourTicket/TourTicketDetail/components/ChoiceTicketBox.js
  src/pages/TourTicket/TourTicketDetail/components/DatePickerBox.js
  src/pages/TourTicket/TourTicketDetail/components/FloatingBox.js
  src/pages/TourTicket/TourTicketDetail/components/ProductInfo.js
  src/pages/TourTicket/TourTicketDetail/components/ReviewContainer.js
  src/pages/TourTicket/TourTicketDetail/components/ReviewPhoto.js
  src/pages/TourTicket/TourTicketDetail/components/ScrollTab.js
  src/pages/TourTicket/TourTicketDetail/components/ShareModal.js
  src/pages/TourTicket/TourTicketDetail/components/TicketOption.js
Labels: Status: 리뷰 요청

#46 [이욱창] 아코디언 백엔드에 맞게 변수명 수정
  src/components/Footer/Footer.js
  src/components/List/Collapse.js
  src/hooks/tourTicketHook.js
  src/pages/TourTicket/TourTicketList.js
  src/pages/TourTicket/components/TourTicketCategory.js
  src/store/tourTicketSlice.js
Labels: Status: 리뷰 요청

#47 [이욱창] 투어티켓 메인 인풋창 레이아웃 구현
  src/components/TopNav/components/UpperNav.js
  src/components/TopNav/navListData.json
Labels: Status: Rebase 요청

#32 [이원국] [리스트] 도시 리스트: 메인 페이지 레이아웃 및 컴포넌트 구현
  public/data/citymain.json
  public/data/magazine.json
  public/data/multicarousel/multi1.json
  public/data/multicarousel/multi2.json
  public/data/multicarousel/multi3.json
  public/data/multicarousel/multi4.json
  public/data/multicarousel/multi5.json
  public/data/multicarousel/multi6.json
  public/data/multicarousel/multi7.json
  public/data/seoultourticket.json
  public/data/spot.json
  public/images/bg.jpg
  public/images/service-1.png
  public/images/service-2.png
  public/images/service-3.png
  public/images/service-4.png
  public/images/subCategories/0.png
  public/images/subCategories/1.png
  public/images/subCategories/2.png
  public/images/subCategories/3.png
  public/images/subCategories/4.png
  public/images/subCategories/5.png
  public/images/subCategories/6.png
  public/images/subCategories/7.png
  public/images/subCategories/8.png
  public/images/subCategories/9.png
  public/images/subCategories/notinuse/1.png
  public/images/subCategories/notinuse/10.png
  public/images/subCategories/notinuse/2.png
  public/images/subCategories/notinuse/3.png
  public/images/subCategories/notinuse/4.png
  public/images/subCategories/notinuse/5.png
  public/images/subCategories/notinuse/6.png
  public/images/subCategories/notinuse/7.png
  public/images/subCategories/notinuse/8.png
  public/images/subCategories/notinuse/9.png
  src/Routes.js
  src/components/Carousel/Cards.js
  src/components/Carousel/Carousel.js
  src/components/Carousel/MultiCarousel.js
  src/components/Carousel/defaultOptions.js
  src/components/SectionHeader/SectionHeader.js
  src/components/TopNav/TopNav.js
  src/pages/Cities/Cities.js
  src/pages/Cities/MainCategories.js
  src/pages/Cities/ServiceButtons.js
  src/pages/Cities/SubCategories.js
  src/pages/Main/Events/Events.js
  src/pages/Main/Main.js
  src/pages/TourTicket/TourTicket.js
  src/pages/WishList/WishList.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#49 [이원국] [공용] 페이지 이동시 스플래시 화면 개선
  public/images/splash_bg.jpeg
  src/Routes.js
  src/components/Splash/GeneralSplash.js
Labels: Status: 리뷰 요청

#54 [이은정] fetch 경로 수정
  src/pages/TourTicket/TourTicketDetail/TourTicketDetail.js
  src/pages/TourTicket/TourTicketDetail/components/FloatingBox.js
Labels: Status: 리뷰 요청

#56 [URGENT] 발표 전 긴급 수정
  src/components/Carousel/Cards.js
  src/components/Carousel/Carousel.js
  src/components/List/ListFilter.js
  src/components/List/components/DateFilters.js
  src/pages/Cities/Cities.js
  src/pages/Cities/MainCategories.js
  src/pages/Main/Main.js
  src/pages/TourTicket/TourTicket.js
  src/pages/TourTicket/TourTicketDetail/TourTicketDetail.js
  src/pages/TourTicket/TourTicketList.js
  src/pages/WishList/WishList.js
  src/pages/WishList/components/EmptyList.js
  src/utils/ApiCall.js
  src/utils/ScrollToTop.js
Labels: Status: 리뷰 요청

#9 [이민재] 회원가입: 레이아웃, 소셜 api를 이용한 회원가입 기능 구현 중
  public/index.html
  src/pages/User/Profile/ProfileSection/ManagingProfileMainSection.js
  src/pages/User/SignUp.js
Labels: Status: 기능 구현중

#57 [이은정] 디테일 리팩토링 중
  public/data/optionMock.json
  src/pages/TourTicket/TourTicketDetail/TourTicketDetail.js
  src/pages/TourTicket/TourTicketDetail/components/ChoiceTicketBox.js
  src/pages/TourTicket/TourTicketDetail/components/FloatingBox.js
  src/pages/TourTicket/TourTicketDetail/components/ReviewContainer.js
  src/pages/TourTicket/TourTicketDetail/components/ScrollTab.js
Labels: Status: 리뷰 요청

#59 [이민재] sign-in 리팩토링
  src/pages/User/Profile/ManagingProfile.js
  src/pages/User/Profile/ProfileSection/EditingProfileMainSection.js
  src/pages/User/SignIn.js
  src/pages/User/SignUp.js
  src/styles/theme.js
  src/utils/Kakao.js
Labels: Statue: Refactoring 진행 중

#60 Fixed: API 연결 bug fixed
  public/index.html
  src/pages/Cities/Cities.js
  src/pages/TourTicket/TourTicketDetail/components/DatePickerBox.js
  src/pages/TourTicket/TourTicketList.js
  src/pages/TourTicket/components/TourTicketCategory.js
  src/pages/WishList/WishList.js
  src/store/tourTicketSlice.js
Labels: Statue: Refactoring 진행 중

#61 Fixed: fixed minor bugs
  src/components/Carousel/Cards.js
  src/pages/TourTicket/TourTicketDetail/components/FloatingBox.js
  src/pages/TourTicket/TourTicketList.js
  src/store/index.js
Labels: Status: 리뷰 요청

#63 [프로필] Refactoring - 불필요한 console.log / 잘못된 색상 변경
  src/pages/User/Profile/AuthenticationPage/AuthenticationPage.js
  src/pages/User/Profile/EditingProfile.js
  src/pages/User/Profile/ManagingProfile.js
  src/pages/User/Profile/ProfileSection/EditingProfileMainSection.js
  src/pages/User/Profile/ProfileSection/ManagingProfileMainSection.js
  src/pages/User/Profile/ProfileSection/SideProfileSection.js
  src/pages/User/SignIn.js
  src/pages/User/SignUp.js
  src/styles/theme.js
Labels: Status: 리뷰 요청
